name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: ilteoood/docker_buildx@master
        name: Build & push Docker image
        with:
          publish: true
          imageName: miclon/fastrpc
          tag: latest
          platform: linux/amd64,linux/arm64,linux/arm/v7
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
